"use strict";

/* ============================================================
   RePixel — textos de la interfaz
   Un objeto por idioma. Lo que le falte a un idioma cae al de por defecto
   clave por clave (lo hace `traducir` en logica.js), así que se puede añadir
   un idioma traduciendo solo los botones y dejar las notas para después.

   Convenios de las cadenas:
   - {hueco} se sustituye por el dato que se pase.
   - "singular|plural" elige por el dato {n}.
   No se traducen los nombres de los pasos (ReFondo, ReSize, ReVer, RePalette,
   ReBloques) ni el vocabulario que ya es el mismo en todas partes: OKLab,
   Sobel, Floyd–Steinberg, Bayer, ZX Spectrum, MSX, NES, metallic, smoothness.
   ============================================================ */
const IDIOMA_POR_DEFECTO = "en";

const IDIOMAS = {
  en: {
    nombre: "English",
    textos: {
      "app.lema": "Pixel art asset pipeline. Everything runs in your browser.",

      /* --- Barra de herramientas --- */
      "herr.titulo": "Tools",
      "herr.plegarTodo": "Collapse all",
      "herr.desplegarTodo": "Expand all",
      "herr.plegar": "Collapse",
      "herr.desplegar": "Expand",
      "herr.apagado": "off",

      /* --- Imágenes --- */
      "img.titulo": "Images",
      "img.soltar": "Drop images or folders here",
      "img.archivosTitulo": "Choose image files",
      "img.carpetaTitulo": "Choose a folder",
      "img.vaciarTitulo": "Remove every loaded image",
      "img.cuantas": "{n} image|{n} images",
      "img.ninguna": "No images found.",
      "img.noSePudo": "Could not read {nombre}",

      /* --- ReFondo --- */
      "fondo.nota": "Erases the flat background: which color, and what counts as outside.",
      "fondo.cuando": "When",
      "fondo.antes": "Before ReSize",
      "fondo.despues": "After ReSize",
      "fondo.notaOrden": "Before: cleaner edge. After: better if the background is noisy.",
      "fondo.color": "Color",
      "fondo.auto": "Auto (from the frame)",
      "fondo.manual": "Manual",
      "fondo.colorTitulo": "Background color by hand",
      "fondo.tomarTitulo": "Copy the detected color here",
      "fondo.alcance": "Scope",
      "fondo.fuera": "Outside only",
      "fondo.todo": "All of that color",
      "fondo.tolerancia": "Tolerance",
      "fondo.desvanecer": "Fade",
      "fondo.notaFade": "Raise it to eat the halo that resizing leaves behind.",
      "fondo.resumen": "{color} · {alcance} · tol {tolerancia}",
      "fondo.resumenAuto": "auto",
      "fondo.resumenFuera": "outside",
      "fondo.resumenTodo": "all",
      "fondo.resumenDespues": " · after ReSize",
      "fondo.sinColor": "Not one opaque pixel in the frame: no background color to find.",
      "fondo.info": "{hex} ({origen}) · {alcance} · {px} px removed ({porcentaje} %)",
      "fondo.origenMarco": "frame",
      "fondo.origenMano": "by hand",

      /* --- ReSize --- */
      "resize.tamano": "Size",
      "resize.rapido": "Quick",
      "resize.proporcion": "Keep aspect ratio",
      "resize.metodo": "Method",
      "resize.area": "Area average",
      "resize.vecino": "Nearest neighbor",
      "resize.alfaDura": "1-bit alpha",
      "resize.umbral": "Threshold",
      "resize.notaAlfa": "Binary alpha: a pixel is either in the silhouette or out.",
      "resize.resumen": "{ancho}×{alto} · {metodo}",
      "resize.resumenArea": "area",
      "resize.resumenVecino": "nearest",
      "resize.resumenAlfa": " · 1-bit alpha",

      /* --- ReVer --- */
      "ver.nota": "Two channels: color gets palettized, edges only get blended in.",
      "ver.canalColor": "Color channel",
      "ver.brillo": "Brightness",
      "ver.contraste": "Contrast",
      "ver.saturacion": "Saturation",
      "ver.tono": "Hue",
      "ver.restablecerTitulo": "Back to neutral color settings",
      "ver.canalBordes": "Edge channel",
      "ver.metodo": "Method",
      "ver.sobel": "Sobel",
      "ver.laplaciano": "Laplacian",
      "ver.difColor": "Color difference",
      "ver.umbral": "Threshold",
      "ver.silueta": "Include the silhouette",
      "ver.influye": "Blend",
      "ver.oscurecer": "Darken",
      "ver.aclarar": "Lighten",
      "ver.realce": "Enhance",
      "ver.influencia": "Amount",
      "ver.notaBordes": "Edges come from the source image, not the adjusted one.",
      "ver.resumenAjustes": "{n} setting|{n} settings",
      "ver.resumenLimpio": "color untouched",
      "ver.resumenBordes": " · edges {metodo} {influencia} %",
      "ver.resumenSinBordes": " · no edges",
      "ver.infoSinBordes": "{color} · no edge channel",
      "ver.info": "{color} · edges on {px} px ({porcentaje} %), {modo} at {influencia} %",
      "ver.modoOscurecer": "darkening",
      "ver.modoAclarar": "lightening",
      "ver.modoRealce": "enhancing",

      /* --- RePalette --- */
      "paleta.entrada": "Lospec URL, slug or hex codes",
      "paleta.cargarTitulo": "Load the palette written above",
      "paleta.archivoTitulo": "Open a palette saved on disk",
      "paleta.formatos": ".gpl · .pal · .hex · .txt · .act · or an image of swatches",
      "paleta.reciente": "Use this palette",
      "paleta.nombre": "{nombre} — {n} colors",
      "paleta.distancia": "Distance",
      "paleta.oklab": "OKLab (perceptual)",
      "paleta.rgb": "Weighted RGB (fast)",
      "paleta.dithering": "Dithering",
      "paleta.ninguno": "None",
      "paleta.bayer": "Bayer 8×8",
      "paleta.intensidad": "Amount",
      "paleta.manual": "Manual ({n} colors)",
      "paleta.sinPaleta": "no palette",
      "paleta.noEntiendo": "I don't understand that palette: paste a Lospec URL or hex codes.",
      "paleta.cargando": "Loading palette from Lospec…",
      "paleta.sinRed": "Could not download it (offline or CORS?). On Lospec use «Copy hex codes» and paste them here.",
      "paleta.noAse": "I can't read .ase or .aseprite: save the palette as .gpl, .pal, .hex or .png.",
      "paleta.imagenVacia": "That image has no opaque pixel to take colors from.",
      "paleta.recorte": "That image has many colors: keeping the first {n}.",
      "paleta.noFichero": "I don't understand that file. Try .gpl, .pal, .hex, .txt, .act or an image of swatches.",

      /* --- ReBloques --- */
      "bloques.nota": "At most N colors per block, taken from the block itself.",
      "bloques.maquina": "Machine",
      "bloques.spectrum": "ZX Spectrum · 8×8 · 2 colors",
      "bloques.msx": "MSX SCREEN 2 · 8×1 · 2 colors",
      "bloques.nes": "NES · 16×16 · 4 colors",
      "bloques.medida": "Custom",
      "bloques.bloque": "Block",
      "bloques.colores": "Colors",
      "bloques.porBloque": "per block",
      "bloques.elegir": "Keep",
      "bloques.error": "Least error",
      "bloques.frecuencia": "Most frequent",
      "bloques.notaCriterio": "«Least error» saves the highlight; «most frequent» spends it on another dark.",
      "bloques.resumen": "{maquina} · {ancho}×{alto} · {colores} colors",
      "bloques.info": "{ancho}×{alto} · {colores} colors · {criterio} — {tocados} of {total} blocks touched ({porcentaje} %), {cambiados} px changed",
      "bloques.criterioError": "least error",
      "bloques.criterioFrecuencia": "most frequent",

      /* --- Máscaras --- */
      "mascaras.titulo": "RGB masks",
      "mascaras.nota": "R metallic · G smoothness · B emissive, from the final image.",
      "mascaras.fuente": "Source",
      "mascaras.brillo": "Brightness",
      "mascaras.contraste": "Contrast",
      "mascaras.invertir": "Invert",
      "mascaras.umbral": "Threshold",
      "mascaras.restablecerTitulo": "Back to the default masks",
      "mascaras.resumen": "{n}/3 channels",
      "mascaras.aNegro": " — black: {canales}",
      "canal.metallic": "Metallic",
      "canal.smoothness": "Smoothness",
      "canal.emisivo": "Emissive",
      "fuente.luminancia": "Luminance",
      "fuente.maximo": "Max (RGB)",
      "fuente.saturacion": "Saturation",
      "fuente.rojo": "Red",
      "fuente.verde": "Green",
      "fuente.azul": "Blue",

      /* --- Vista previa --- */
      "vista.titulo": "View",
      "vista.alejar": "Zoom out",
      "vista.acercar": "Zoom in",
      "vista.ajustarTitulo": "Back to fit (or double click a view)",
      "vista.ayuda": "Wheel: zoom · drag: pan · all views in sync",
      "vista.ajustado": " · fit",
      "vista.original": "Original",
      "vista.resultado": "Result",
      "vista.infoColores": " — {n} colors",
      "vista.fondoTitulo": "What ReFondo removed",
      "vista.fondoNota": "white is what goes",
      "vista.fondoMapa": "Detected background",
      "vista.fondoSin": "Without background",
      "vista.verTitulo": "What RePixel sees",
      "vista.verColor": "Color channel",
      "vista.verBordes": "Edge channel",
      "vista.verEntrada": "Into RePalette",
      "vista.bloquesTitulo": "Attribute clash",
      "vista.bloquesNota": "white is how much each block changed",
      "vista.bloquesAntes": "No limit",
      "vista.bloquesMapa": "Blocks touched",
      "vista.mascarasTitulo": "Mask texture",
      "vista.mezcla": "Blend",

      /* --- Descargas --- */
      "salida.sufijo": "Suffix",
      "salida.sufijoMascara": "Masks",
      "salida.descargarTitulo": "Download the image being previewed",
      "salida.zipTitulo": "Download every image in a ZIP",
      "salida.procesando": "Processing {i}/{n}…",
    },
  },

  es: {
    nombre: "Español",
    textos: {
      "app.lema": "Pipeline de assets pixel art. Todo se procesa en local.",

      "herr.titulo": "Herramientas",
      "herr.plegarTodo": "Plegar todo",
      "herr.desplegarTodo": "Desplegar todo",
      "herr.plegar": "Plegar",
      "herr.desplegar": "Desplegar",
      "herr.apagado": "apagado",

      "img.titulo": "Imágenes",
      "img.soltar": "Arrastra imágenes o carpetas aquí",
      "img.archivosTitulo": "Elegir imágenes sueltas",
      "img.carpetaTitulo": "Elegir una carpeta entera",
      "img.vaciarTitulo": "Quitar todas las imágenes cargadas",
      "img.cuantas": "{n} imagen|{n} imágenes",
      "img.ninguna": "No se encontraron imágenes.",
      "img.noSePudo": "No se pudo leer {nombre}",

      "fondo.nota": "Borra el fondo plano: qué color y qué es «fuera».",
      "fondo.cuando": "Cuándo",
      "fondo.antes": "Antes de ReSize",
      "fondo.despues": "Después de ReSize",
      "fondo.notaOrden": "Antes: el borde sale limpio. Después: mejor si el fondo trae ruido.",
      "fondo.color": "Color",
      "fondo.auto": "Automático (el del marco)",
      "fondo.manual": "A mano",
      "fondo.colorTitulo": "Color de fondo a mano",
      "fondo.tomarTitulo": "Copiar aquí el color detectado",
      "fondo.alcance": "Alcance",
      "fondo.fuera": "Solo lo de fuera",
      "fondo.todo": "Todo ese color",
      "fondo.tolerancia": "Tolerancia",
      "fondo.desvanecer": "Desvanecer",
      "fondo.notaFade": "Súbelo para comerte el halo que deja el reescalado.",
      "fondo.resumen": "{color} · {alcance} · tol {tolerancia}",
      "fondo.resumenAuto": "auto",
      "fondo.resumenFuera": "solo fuera",
      "fondo.resumenTodo": "todo el color",
      "fondo.resumenDespues": " · tras ReSize",
      "fondo.sinColor": "Ni un píxel opaco en el marco: no sé de qué color es el fondo.",
      "fondo.info": "{hex} ({origen}) · {alcance} · {px} px quitados ({porcentaje} %)",
      "fondo.origenMarco": "del marco",
      "fondo.origenMano": "a mano",

      "resize.tamano": "Tamaño",
      "resize.rapido": "Rápido",
      "resize.proporcion": "Mantener proporción",
      "resize.metodo": "Método",
      "resize.area": "Promedio de área",
      "resize.vecino": "Vecino más cercano",
      "resize.alfaDura": "Alfa de 1 bit",
      "resize.umbral": "Umbral",
      "resize.notaAlfa": "Alfa binaria: cada píxel entra en la silueta o no entra.",
      "resize.resumen": "{ancho}×{alto} · {metodo}",
      "resize.resumenArea": "área",
      "resize.resumenVecino": "vecino",
      "resize.resumenAlfa": " · alfa 1 bit",

      "ver.nota": "Dos canales: el de color se palettiza, el de bordes solo se mezcla.",
      "ver.canalColor": "Canal de color",
      "ver.brillo": "Brillo",
      "ver.contraste": "Contraste",
      "ver.saturacion": "Saturación",
      "ver.tono": "Tono",
      "ver.restablecerTitulo": "Dejar el color sin tocar",
      "ver.canalBordes": "Canal de bordes",
      "ver.metodo": "Método",
      "ver.sobel": "Sobel",
      "ver.laplaciano": "Laplaciano",
      "ver.difColor": "Diferencia de color",
      "ver.umbral": "Umbral",
      "ver.silueta": "Incluir la silueta",
      "ver.influye": "Influye",
      "ver.oscurecer": "Oscureciendo",
      "ver.aclarar": "Aclarando",
      "ver.realce": "Realzando",
      "ver.influencia": "Influencia",
      "ver.notaBordes": "Los bordes salen de la imagen de partida, no de la ajustada.",
      "ver.resumenAjustes": "{n} ajuste|{n} ajustes",
      "ver.resumenLimpio": "color sin tocar",
      "ver.resumenBordes": " · bordes {metodo} {influencia} %",
      "ver.resumenSinBordes": " · sin bordes",
      "ver.infoSinBordes": "{color} · sin canal de bordes",
      "ver.info": "{color} · bordes en {px} px ({porcentaje} %), {modo} al {influencia} %",
      "ver.modoOscurecer": "oscureciendo",
      "ver.modoAclarar": "aclarando",
      "ver.modoRealce": "realzando",

      "paleta.entrada": "URL de Lospec, slug o códigos hex",
      "paleta.cargarTitulo": "Cargar la paleta escrita arriba",
      "paleta.archivoTitulo": "Abrir una paleta guardada en el disco",
      "paleta.formatos": ".gpl · .pal · .hex · .txt · .act · o una imagen de muestras",
      "paleta.reciente": "Usar esta paleta",
      "paleta.nombre": "{nombre} — {n} colores",
      "paleta.distancia": "Distancia",
      "paleta.oklab": "OKLab (perceptual)",
      "paleta.rgb": "RGB ponderado (rápido)",
      "paleta.dithering": "Dithering",
      "paleta.ninguno": "Ninguno",
      "paleta.bayer": "Bayer 8×8",
      "paleta.intensidad": "Intensidad",
      "paleta.manual": "Manual ({n} colores)",
      "paleta.sinPaleta": "sin paleta",
      "paleta.noEntiendo": "No entiendo esa paleta: pega una URL de Lospec o códigos hex.",
      "paleta.cargando": "Cargando paleta de Lospec…",
      "paleta.sinRed": "No se pudo descargar (¿sin conexión o CORS?). En Lospec usa «Copy hex codes» y pégalos aquí.",
      "paleta.noAse": "Los .ase y .aseprite no los leo: guarda la paleta como .gpl, .pal, .hex o .png.",
      "paleta.imagenVacia": "Esa imagen no tiene ni un píxel opaco del que sacar colores.",
      "paleta.recorte": "Esa imagen trae muchos colores: me quedo con los {n} primeros.",
      "paleta.noFichero": "No entiendo ese fichero. Valen .gpl, .pal, .hex, .txt, .act o una imagen de muestras.",

      "bloques.nota": "Como mucho N colores por bloque, salidos del propio bloque.",
      "bloques.maquina": "Máquina",
      "bloques.spectrum": "ZX Spectrum · 8×8 · 2 colores",
      "bloques.msx": "MSX SCREEN 2 · 8×1 · 2 colores",
      "bloques.nes": "NES · 16×16 · 4 colores",
      "bloques.medida": "A medida",
      "bloques.bloque": "Bloque",
      "bloques.colores": "Colores",
      "bloques.porBloque": "por bloque",
      "bloques.elegir": "Salvar",
      "bloques.error": "Los que menos error dejan",
      "bloques.frecuencia": "Los más repetidos",
      "bloques.notaCriterio": "«Menos error» salva el brillo; «más repetidos» lo gasta en otro oscuro.",
      "bloques.resumen": "{maquina} · {ancho}×{alto} · {colores} colores",
      "bloques.info": "{ancho}×{alto} · {colores} colores · {criterio} — {tocados} de {total} bloques tocados ({porcentaje} %), {cambiados} px cambiados",
      "bloques.criterioError": "menos error",
      "bloques.criterioFrecuencia": "los más repetidos",

      "mascaras.titulo": "Máscaras RGB",
      "mascaras.nota": "R metallic · G smoothness · B emisivo, sobre el resultado final.",
      "mascaras.fuente": "Fuente",
      "mascaras.brillo": "Brillo",
      "mascaras.contraste": "Contraste",
      "mascaras.invertir": "Invertir",
      "mascaras.umbral": "Umbral",
      "mascaras.restablecerTitulo": "Dejar las máscaras como venían",
      "mascaras.resumen": "{n}/3 canales",
      "mascaras.aNegro": " — a negro: {canales}",
      "canal.metallic": "Metallic",
      "canal.smoothness": "Smoothness",
      "canal.emisivo": "Emisivo",
      "fuente.luminancia": "Luminancia",
      "fuente.maximo": "Máximo (RGB)",
      "fuente.saturacion": "Saturación",
      "fuente.rojo": "Rojo",
      "fuente.verde": "Verde",
      "fuente.azul": "Azul",

      "vista.titulo": "Vista",
      "vista.alejar": "Alejar",
      "vista.acercar": "Acercar",
      "vista.ajustarTitulo": "Volver al ajuste (o doble clic en una vista)",
      "vista.ayuda": "Rueda: zoom · arrastrar: mover · todas sincronizadas",
      "vista.ajustado": " · ajustado",
      "vista.original": "Original",
      "vista.resultado": "Resultado",
      "vista.infoColores": " — {n} colores",
      "vista.fondoTitulo": "Lo que ReFondo ha quitado",
      "vista.fondoNota": "en blanco, lo que se va",
      "vista.fondoMapa": "Fondo detectado",
      "vista.fondoSin": "Sin fondo",
      "vista.verTitulo": "Lo que ve RePixel",
      "vista.verColor": "Canal de color",
      "vista.verBordes": "Canal de bordes",
      "vista.verEntrada": "Entrada a RePalette",
      "vista.bloquesTitulo": "Clash de atributos",
      "vista.bloquesNota": "en blanco, cuánto ha mordido cada bloque",
      "vista.bloquesAntes": "Sin límite",
      "vista.bloquesMapa": "Bloques tocados",
      "vista.mascarasTitulo": "Textura de máscaras",
      "vista.mezcla": "Mezcla",

      "salida.sufijo": "Sufijo",
      "salida.sufijoMascara": "Máscaras",
      "salida.descargarTitulo": "Descargar la imagen de la vista previa",
      "salida.zipTitulo": "Descargar todas las imágenes en un ZIP",
      "salida.procesando": "Procesando {i}/{n}…",
    },
  },
};
